sudo: required

language: node_js

services:
  - docker

node_js:
  - "4.1"
  - "4.0"
  - "0.12"

before_install:
 #- node server.js &
  - docker build -t docker_node .
  - docker ps -a
  - docker run -i docker_node /bin/sh -c "cd /; ./startup_node.sh"

install: true
  #- npm install
  #- npm install -g mocha
  #- mocha test

script: true
  #- mocha /usr/src/node_server/test.js