sudo: required

language: node_js

services:
  - docker

node_js:
  - "4.1"
  - "4.0"
  - "0.12"

script:
 #- node server.js &
  - docker build -t docker_node .
  - docker run -dt -p 3002:3002 docker_node /bin/sh -c "cd "

install: true
  #- npm install
  #- npm install -g mocha
  #- mocha test

script: true
  #- mocha /usr/src/node_server/test.js